### ISSUE TITLE
프로젝트 기초 개발 환경을 설정합니다.

### ISSUE THREAD

**Issue by yu-heejin** [ddwu-aws-cloud-club/team-b#1]
## TODO ✏️
- [x] #2
- [x] JPA, QueryDSL 설정하기
- [x] Dockerfile, docker-compose 설정하기
- [x] .yml 파일 설정하기
- [x] 실행 스크립트 추가하기
