### ISSUE TITLE
Student CRUD 기능 구현하기

### ISSUE THREAD

**Issue by ParkSenn** [ddwu-aws-cloud-club/team-b#3]
## Description 📝
H2와 SpringData Jpa를 사용하여 Student 엔티티의 CRUD 기능을 구현해야 합니다. 각 기능은 다음과 같습니다:
- Create: 새로운 학생을 추가합니다.
- Read: 모든 학생의 목록을 조회하거나, 특정 학생의 정보를 조회할 수 있어야 합니다.
- Update: 특정 학생의 정보를 업데이트합니다.
- Delete: 특정 학생을 삭제합니다.

## TODO ✅
- [ ] H2 관련 application.yml 작성
- [ ] Student 엔티티 생성
- [ ] StudentRepository 인터페이스 작성
- [ ] StudentService에서 CRUD 기능 구현
- [ ] StudentController 작성
- [ ] SpringConfig 작성
